BATCH_SIZE = 4
NUMBER_CLASSES = 2
INPUT_SHAPE_IMAGE = (352, 352, 3)
EPOCHS = 200
AUGMENTATION_DATA = True

JSON_FILE_NAME = 'data.json'
IMAGES_PATH = 'images'
MASKS_PATH = 'masks'

DATASETS = ['first_data']

LEARNING_RATE = 0.0001
BACKBONE = 'resnet18'
ENCODER_WEIGHTS = 'imagenet'
OUTPUT_ACTIVATION = 'softmax'
LAYER_ACTIVATION = 'relu'
MODEL_NAME = 'Unet'
SAVE_MODEL_EVERY_EPOCH = False

LOGS = 'logs'
SAVE_MODELS = 'save_models'
